/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels.medicalrecord;

import main.ShelterManager;
import model.Animal;
import model.MedicalRecordModel;
import java.awt.Color;
import java.time.LocalDate;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Nat
 */
public class AddMedicalRecord extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicalRecord
     */
    private ShelterManager shelterManager;

    public AddMedicalRecord(ShelterManager manager) {
        initComponents();

        this.shelterManager = manager;

        jtfAnimalId.setEditable(false);
        jtfAnimalId.setBackground(new Color(230, 230, 230));

        // Fill the dropdown with animals
        populateAnimalDropdown();

        // --- 1. AUTO-SET DATE and clear form ---
        clearForm();
    }

    private void populateAnimalDropdown() {
        ArrayList<Animal> animals = shelterManager.getAnimals();
        jcbAnimalSelect.removeAllItems();
        jcbAnimalSelect.addItem("Select an animal..."); // Add a placeholder
        for (Animal a : animals) {
            jcbAnimalSelect.addItem(a); // Uses Animal's toString() method
        }
    }

    private void clearForm() {
        jcbAnimalSelect.setSelectedIndex(0); // Reset to "Select an animal..."
        jtfAnimalId.setText("");
        jtaDiagnosis.setText("");
        jtaTreatment.setText("");

        // --- 2. AUTO-SET DATE (using jTextField2) ---
        jTextField2.setText(LocalDate.now().toString());
        jTextField2.setEditable(false);
        jTextField2.setBackground(new Color(230, 230, 230));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clearFieldsBtn = new javax.swing.JButton();
        jcbAnimalSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfAnimalId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDiagnosis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaTreatment = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveRecord1 = new javax.swing.JButton();

        clearFieldsBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clearFieldsBtn.setText("Clear Fields");
        clearFieldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsBtnActionPerformed(evt);
            }
        });

        jcbAnimalSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAnimalSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAnimalSelectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Animal:");

        jtaDiagnosis.setColumns(20);
        jtaDiagnosis.setRows(5);
        jScrollPane1.setViewportView(jtaDiagnosis);

        jtaTreatment.setColumns(20);
        jtaTreatment.setRows(5);
        jScrollPane2.setViewportView(jtaTreatment);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Animal Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Diagnosis:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Treatment:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("ADD MEDICAL RECORD");

        btnSaveRecord1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSaveRecord1.setText("Save");
        btnSaveRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecord1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jtfAnimalId)
                            .addComponent(jcbAnimalSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearFieldsBtn)
                .addGap(245, 245, 245))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(535, Short.MAX_VALUE)
                    .addComponent(btnSaveRecord1)
                    .addGap(144, 144, 144)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAnimalSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAnimalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(62, 62, 62)
                .addComponent(clearFieldsBtn)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(641, Short.MAX_VALUE)
                    .addComponent(btnSaveRecord1)
                    .addGap(79, 79, 79)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAnimalSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAnimalSelectActionPerformed

        Object selectedItem = jcbAnimalSelect.getSelectedItem();
        if (selectedItem instanceof Animal) {
            Animal selectedAnimal = (Animal) selectedItem;
            // Update the read-only text field
            jtfAnimalId.setText(String.valueOf(selectedAnimal.getId()));
        } else {
            // "Select an animal..." was chosen
            jtfAnimalId.setText("");
        }
    }//GEN-LAST:event_jcbAnimalSelectActionPerformed

    private void clearFieldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsBtnActionPerformed

        int choice = JOptionPane.showConfirmDialog(
                this, // Parent component
                "Are you sure you want to clear this form?", // Message
                "Confirm Clear", // Title
                JOptionPane.YES_NO_OPTION, // Button type
                JOptionPane.WARNING_MESSAGE // Message type
        );

        // Check if the user clicked "Yes"
        if (choice == JOptionPane.YES_OPTION) {
            clearForm();
        }
    }//GEN-LAST:event_clearFieldsBtnActionPerformed

    private void btnSaveRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecord1ActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validate animal selection
            Object selectedItem = jcbAnimalSelect.getSelectedItem();
            if (!(selectedItem instanceof Animal)) {
                JOptionPane.showMessageDialog(this, "Please select an animal.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Animal selectedAnimal = (Animal) selectedItem;
            int animalId = selectedAnimal.getId();

            // 2. Validate text fields
            String diagnosis = jtaDiagnosis.getText().trim();
            String treatment = jtaTreatment.getText().trim();
            if (diagnosis.isEmpty() || treatment.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Diagnosis and Treatment cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Get auto-generated data
            int recordId = shelterManager.getNextMedicalRecordId();
            LocalDate date = LocalDate.parse(jTextField2.getText()); // Safe because we set it

            // 4. Create new MedicalRecordModel object
            // (Assuming "notes" can be an empty string)
            MedicalRecordModel newRecord = new MedicalRecordModel(recordId, animalId, diagnosis, treatment, date, "");

            // 5. Add via manager (which saves to JSON)
            shelterManager.addMedicalRecord(newRecord);

            // 6. Show success and clear form
            JOptionPane.showMessageDialog(this, "Medical record (ID: " + recordId + ") saved successfully for " + selectedAnimal.getName() + ".", "Success", JOptionPane.INFORMATION_MESSAGE);
            clearForm();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred while saving: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveRecord1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveRecord1;
    private javax.swing.JButton clearFieldsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<Object> jcbAnimalSelect;
    private javax.swing.JTextArea jtaDiagnosis;
    private javax.swing.JTextArea jtaTreatment;
    private javax.swing.JTextField jtfAnimalId;
    // End of variables declaration//GEN-END:variables
}
