/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels.medicalrecord;

import main.ShelterManager;
import model.Animal;
import model.MedicalRecord;
import java.awt.Color;
import java.time.LocalDate;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Nat
 */
public class AddMedicalRecord extends javax.swing.JPanel {

    /**
     * Creates new form AddMedicalRecord
     */
    private ShelterManager shelterManager;

    public AddMedicalRecord(ShelterManager manager) {
        initComponents(); // Call this only ONCE at the top

        // Now you can safely save the manager
        this.shelterManager = manager;

        // All your setup code now goes AFTER
        jtfAnimalId.setEditable(false);
        jtfAnimalId.setBackground(new Color(230, 230, 230));

        // Fill the dropdown
        populateAnimalDropdown();
    }

    private void populateAnimalDropdown() {
        ArrayList<Animal> animals = shelterManager.getAnimals(); // This works now
        jcbAnimalSelect.removeAllItems();
        jcbAnimalSelect.addItem("Select an animal...");
        for (Animal a : animals) {
            jcbAnimalSelect.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSaveRecord = new javax.swing.JButton();
        jcbAnimalSelect = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jtfAnimalId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDiagnosis = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaTreatment = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        btnSaveRecord.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSaveRecord.setText("Save");
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        jcbAnimalSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbAnimalSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAnimalSelectActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Animal:");

        jtaDiagnosis.setColumns(20);
        jtaDiagnosis.setRows(5);
        jScrollPane1.setViewportView(jtaDiagnosis);

        jtaTreatment.setColumns(20);
        jtaTreatment.setRows(5);
        jScrollPane2.setViewportView(jtaTreatment);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Animal Id:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Diagnosis:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Treatment:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Date:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("ADD MEDICAL RECORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(btnSaveRecord)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jtfAnimalId)
                            .addComponent(jcbAnimalSelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAnimalSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAnimalId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(54, 54, 54)
                .addComponent(btnSaveRecord)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcbAnimalSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAnimalSelectActionPerformed

        if (jcbAnimalSelect.getSelectedItem() instanceof Animal) {
            // Get the selected Animal object
            Animal selectedAnimal = (Animal) jcbAnimalSelect.getSelectedItem();
            // Set the ID in the non-editable text field
            jtfAnimalId.setText(String.valueOf(selectedAnimal.getId()));
        } else {
            // "Select an animal..." was chosen
            jtfAnimalId.setText("");
        }
    }//GEN-LAST:event_jcbAnimalSelectActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed

        // 1. Get all data from the form
        String animalIdStr = jtfAnimalId.getText();
        String diagnosis = jtaDiagnosis.getText();
        String treatment = jtaTreatment.getText();
        LocalDate date = LocalDate.now();

        // 2. Validate the data
        int animalId;
        if (animalIdStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an animal.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            animalId = Integer.parseInt(animalIdStr);
        }

        if (diagnosis.isBlank() || treatment.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please enter a diagnosis and treatment.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int newId = shelterManager.getNextMedicalRecordId();

        model.MedicalRecord newRecord = new model.MedicalRecord(newId, animalId, diagnosis, treatment, date); 
        shelterManager.addMedicalRecord(newRecord);

        JOptionPane.showMessageDialog(this, "Medical record saved successfully! New ID: " + newId);

        jcbAnimalSelect.setSelectedIndex(0);
        jtfAnimalId.setText("");
        jtaDiagnosis.setText("");
        jtaTreatment.setText("");
    }//GEN-LAST:event_btnSaveRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<Object> jcbAnimalSelect;
    private javax.swing.JTextArea jtaDiagnosis;
    private javax.swing.JTextArea jtaTreatment;
    private javax.swing.JTextField jtfAnimalId;
    // End of variables declaration//GEN-END:variables
}
