/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.panels.adoptionprocess;

import main.ShelterManager;
import model.Adopter;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author Nat
 */
public class AddAdopter extends javax.swing.JPanel {

        private ShelterManager shelterManager;

    /**
     * Creates new form AddAdopter
     */
    public AddAdopter(ShelterManager manager) {
        initComponents();
        this.shelterManager = manager;
        setFormDefaults(); // Call the helper method
    }

    private void setFormDefaults() {
        if (shelterManager != null) {
            // Get and set the next ID
            int nextId = shelterManager.getNextAdopterId();
            idJtf.setText(String.valueOf(nextId));
            idJtf.setEditable(false);
            idJtf.setBackground(new Color(230, 230, 230)); // Make it look disabled

            // Clear other fields
            nameJtf.setText("");
            contactInfoJtf.setText("");
            addressJta.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clearFieldsBtn = new javax.swing.JButton();
        addAdopterBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idJtf = new javax.swing.JTextField();
        nameJtf = new javax.swing.JTextField();
        contactInfoJtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressJta = new javax.swing.JTextArea();

        clearFieldsBtn.setText("Clear Fields");
        clearFieldsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsBtnActionPerformed(evt);
            }
        });

        addAdopterBtn.setText("Add Adopter");
        addAdopterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdopterBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Contact Information:");

        jLabel4.setText("Address:");

        addressJta.setColumns(20);
        addressJta.setRows(5);
        jScrollPane1.setViewportView(addressJta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearFieldsBtn)
                .addGap(30, 30, 30)
                .addComponent(addAdopterBtn)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameJtf)
                    .addComponent(idJtf)
                    .addComponent(contactInfoJtf)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contactInfoJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(104, 104, 104)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearFieldsBtn)
                    .addComponent(addAdopterBtn))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void clearFieldsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsBtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to clear all fields?",
            "Confirm Clear",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            setFormDefaults(); // Just call the helper method
        }
    }//GEN-LAST:event_clearFieldsBtnActionPerformed

    private void addAdopterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdopterBtnActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Get ID (it's pre-filled)
            int id = Integer.parseInt(idJtf.getText());

            // 2. Get data and validate
            String name = nameJtf.getText().trim();
            String contact = contactInfoJtf.getText().trim();
            String address = addressJta.getText().trim();

            if (name.isEmpty() || contact.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Name, Contact Info, and Address cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Create Adopter object
            Adopter newAdopter = new Adopter(id, name, contact, address);

            // 4. Add via manager (which also saves)
            shelterManager.addAdopter(newAdopter);

            // 5. Show success and clear form
            JOptionPane.showMessageDialog(this, "Adopter '" + name + "' added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            setFormDefaults(); // Reset form for next entry

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid ID. This should not happen. Please restart.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_addAdopterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdopterBtn;
    private javax.swing.JTextArea addressJta;
    private javax.swing.JButton clearFieldsBtn;
    private javax.swing.JTextField contactInfoJtf;
    private javax.swing.JTextField idJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameJtf;
    // End of variables declaration//GEN-END:variables
}
