/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.frames;

import java.io.*;
import java.awt.*;
import javax.swing.JOptionPane;
import main.ShelterManager;
import ui.panels.animalmanagement.AnimalProfiles;
import ui.panels.adoptionprocess.AdoptionRecords;
import ui.panels.adoptionprocess.ProcessAdoption;

/**
 *
 * @author Aspire-5
 */
public class AdoptionProcessFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdoptionProcessFrame
     */
    public AdoptionProcessFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

        // --- CALL THE PANEL'S DEFAULT CONSTRUCTOR ---
        showForm(new AdoptionRecords());

        System.out.println("Pass: ADOPTION PROCESSING - View Adoption Records");
    }

    //  private static FontSetter fs = new FontSetter();
    public void showForm(Component com) {
        jBody.removeAll();
        jBody.add(com, BorderLayout.CENTER);
        jBody.revalidate();
        jBody.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adoptionProcessingPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        bantayLbl = new javax.swing.JLabel();
        animalManagementBtn = new javax.swing.JButton();
        adoptionProcessingBtn = new javax.swing.JButton();
        medicalRecordsBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        adoptionRecordsBtn = new javax.swing.JButton();
        processAdoptionBtn = new javax.swing.JButton();
        jBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sidePanel.setForeground(new java.awt.Color(0, 0, 0));
        sidePanel.setToolTipText("");

        bantayLbl.setText("BANTAY");

        animalManagementBtn.setText("Animal Management");
        animalManagementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalManagementBtnActionPerformed(evt);
            }
        });

        adoptionProcessingBtn.setText("Adoption Processing");
        adoptionProcessingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptionProcessingBtnActionPerformed(evt);
            }
        });

        medicalRecordsBtn.setText("Medical Records");
        medicalRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRecordsBtnActionPerformed(evt);
            }
        });

        reportsBtn.setText("Reports");
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(medicalRecordsBtn)
                .addGap(47, 47, 47))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(bantayLbl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addComponent(reportsBtn)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addComponent(animalManagementBtn)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                        .addComponent(adoptionProcessingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bantayLbl)
                .addGap(91, 91, 91)
                .addComponent(animalManagementBtn)
                .addGap(18, 18, 18)
                .addComponent(adoptionProcessingBtn)
                .addGap(18, 18, 18)
                .addComponent(medicalRecordsBtn)
                .addGap(18, 18, 18)
                .addComponent(reportsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(30, 30, 30))
        );

        adoptionRecordsBtn.setText("Adoption Records");
        adoptionRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptionRecordsBtnActionPerformed(evt);
            }
        });

        processAdoptionBtn.setText("Process Adoption");
        processAdoptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processAdoptionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(adoptionRecordsBtn)
                .addGap(18, 18, 18)
                .addComponent(processAdoptionBtn)
                .addContainerGap(495, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adoptionRecordsBtn)
                    .addComponent(processAdoptionBtn))
                .addContainerGap())
        );

        jBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout adoptionProcessingPanelLayout = new javax.swing.GroupLayout(adoptionProcessingPanel);
        adoptionProcessingPanel.setLayout(adoptionProcessingPanelLayout);
        adoptionProcessingPanelLayout.setHorizontalGroup(
            adoptionProcessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adoptionProcessingPanelLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adoptionProcessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        adoptionProcessingPanelLayout.setVerticalGroup(
            adoptionProcessingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adoptionProcessingPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adoptionProcessingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adoptionProcessingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalManagementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalManagementBtnActionPerformed
        // TODO add your handling code here:
        ShelterManager manager = new ShelterManager();
        new AnimalManagementFrame(manager).setVisible(true);
        setVisible(false);
        System.out.println("Pass: ANIMAL MANAGEMENT");
    }//GEN-LAST:event_animalManagementBtnActionPerformed

    private void adoptionProcessingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptionProcessingBtnActionPerformed
        // TODO add your handling code here:
        showForm(new AdoptionRecords());
        System.out.println("Pass: ADOPTION PROCESSING - View Adoption Records");
    }//GEN-LAST:event_adoptionProcessingBtnActionPerformed

    private void medicalRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordsBtnActionPerformed
        // TODO add your handling code here:
        new MedicalRecordFrame().setVisible(true);
        setVisible(false);
        System.out.println("Pass: MEDICAL RECORD");
    }//GEN-LAST:event_medicalRecordsBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        // TODO add your handling code here:
        new ReportsFrame().setVisible(true);
        setVisible(false);
        System.out.println("Pass: REPORTS");
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();
            System.out.println("Pass: You have successfully logged out.");
            new LogIn().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void adoptionRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptionRecordsBtnActionPerformed
        showForm(new AdoptionRecords());
        System.out.println("Pass: ADOPTION PROCESSING - View Adoption Records");
    }//GEN-LAST:event_adoptionRecordsBtnActionPerformed

    private void processAdoptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processAdoptionBtnActionPerformed
        showForm(new ProcessAdoption());
        System.out.println("Pass: ADOPTION PROCESSING - Process Adoption");
    }//GEN-LAST:event_processAdoptionBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdoptionProcessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdoptionProcessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdoptionProcessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdoptionProcessFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdoptionProcessFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adoptionProcessingBtn;
    private javax.swing.JPanel adoptionProcessingPanel;
    private javax.swing.JButton adoptionRecordsBtn;
    private javax.swing.JButton animalManagementBtn;
    private javax.swing.JLabel bantayLbl;
    private javax.swing.JPanel jBody;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton medicalRecordsBtn;
    private javax.swing.JButton processAdoptionBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
