/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.frames;

import org.json.simple.*;
import org.json.simple.parser.*;
import java.io.*;
import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.JOptionPane;
import main.ShelterManager;

import ui.panels.animalmanagement.AnimalProfiles;
import ui.panels.medicalrecord.*;

/**
 *
 * @author Aspire-5
 */
public class MedicalRecordFrame extends javax.swing.JFrame {

    private ShelterManager shelterManager;

    /**
     * Creates new form MedicalRecordFrame
     */
    public MedicalRecordFrame(ShelterManager manager) {
        initComponents();

        // --- 3. SAVE THE MANAGER ---
        this.shelterManager = manager;

        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);

        // --- 4. PASS THE MANAGER TO THE PANEL ---
        showForm(new MedicalRecord(this.shelterManager));
        System.out.println("Pass: MEDICAL RECORD - View Medical Records");

    }

    //  private static FontSetter fs = new FontSetter();
    public void showForm(Component com) {
        jBody.removeAll();
        jBody.add(com, BorderLayout.CENTER);
        jBody.revalidate();
        jBody.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adoptionProcessingPanel2 = new javax.swing.JPanel();
        sidePanel2 = new javax.swing.JPanel();
        bantayLbl2 = new javax.swing.JLabel();
        animalManagementBtn2 = new javax.swing.JButton();
        adoptionProcessingBtn2 = new javax.swing.JButton();
        medicalRecordsBtn2 = new javax.swing.JButton();
        reportsBtn2 = new javax.swing.JButton();
        logoutBtn2 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        viewMedicalRecords = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        sidePanel2.setForeground(new java.awt.Color(0, 0, 0));
        sidePanel2.setToolTipText("");

        bantayLbl2.setText("BANTAY");

        animalManagementBtn2.setText("Animal Management");
        animalManagementBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalManagementBtn2ActionPerformed(evt);
            }
        });

        adoptionProcessingBtn2.setText("Adoption Processing");
        adoptionProcessingBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adoptionProcessingBtn2ActionPerformed(evt);
            }
        });

        medicalRecordsBtn2.setText("Medical Records");
        medicalRecordsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRecordsBtn2ActionPerformed(evt);
            }
        });

        reportsBtn2.setText("Reports");
        reportsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtn2ActionPerformed(evt);
            }
        });

        logoutBtn2.setText("Log Out");
        logoutBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanel2Layout = new javax.swing.GroupLayout(sidePanel2);
        sidePanel2.setLayout(sidePanel2Layout);
        sidePanel2Layout.setHorizontalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(medicalRecordsBtn2)
                .addGap(47, 47, 47))
            .addGroup(sidePanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(logoutBtn2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidePanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(bantayLbl2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel2Layout.createSequentialGroup()
                        .addComponent(reportsBtn2)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel2Layout.createSequentialGroup()
                        .addComponent(animalManagementBtn2)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanel2Layout.createSequentialGroup()
                        .addComponent(adoptionProcessingBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        sidePanel2Layout.setVerticalGroup(
            sidePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(bantayLbl2)
                .addGap(91, 91, 91)
                .addComponent(animalManagementBtn2)
                .addGap(18, 18, 18)
                .addComponent(adoptionProcessingBtn2)
                .addGap(18, 18, 18)
                .addComponent(medicalRecordsBtn2)
                .addGap(18, 18, 18)
                .addComponent(reportsBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(logoutBtn2)
                .addGap(30, 30, 30))
        );

        viewMedicalRecords.setText("View Medical Records");
        viewMedicalRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMedicalRecordsActionPerformed(evt);
            }
        });

        jButton1.setText("Add Medical Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(viewMedicalRecords)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewMedicalRecords)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout adoptionProcessingPanel2Layout = new javax.swing.GroupLayout(adoptionProcessingPanel2);
        adoptionProcessingPanel2.setLayout(adoptionProcessingPanel2Layout);
        adoptionProcessingPanel2Layout.setHorizontalGroup(
            adoptionProcessingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adoptionProcessingPanel2Layout.createSequentialGroup()
                .addComponent(sidePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adoptionProcessingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        adoptionProcessingPanel2Layout.setVerticalGroup(
            adoptionProcessingPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adoptionProcessingPanel2Layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(sidePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adoptionProcessingPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adoptionProcessingPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalManagementBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalManagementBtn2ActionPerformed
        // TODO add your handling code here:
        ShelterManager manager = new ShelterManager();
        new AnimalManagementFrame(manager).setVisible(true);
        setVisible(false);
        System.out.println("Pass: ANIMAL MANAGEMENT");
    }//GEN-LAST:event_animalManagementBtn2ActionPerformed

    private void adoptionProcessingBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adoptionProcessingBtn2ActionPerformed
        // TODO add your handling code here:
        ShelterManager manager = new ShelterManager();
        new AdoptionProcessFrame(manager).setVisible(true);
        setVisible(false);
        System.out.println("Pass: ADOPTION PROCESSING - View Adoption Records");
    }//GEN-LAST:event_adoptionProcessingBtn2ActionPerformed

    private void medicalRecordsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordsBtn2ActionPerformed
        // TODO add your handling code here:
        new MedicalRecordFrame(this.shelterManager).setVisible(true);
        this.dispose();
        System.out.println("Pass: MEDICAL RECORD - View Medical Records");
    }//GEN-LAST:event_medicalRecordsBtn2ActionPerformed

    private void reportsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtn2ActionPerformed
        // TODO add your handling code here:
        new ReportsFrame().setVisible(true);
        setVisible(false);
        System.out.println("Pass: REPORTS");
    }//GEN-LAST:event_reportsBtn2ActionPerformed

    private void logoutBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn2ActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Log Out", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();
            System.out.println("Pass: You have successfully logged out.");
            new LogIn().setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_logoutBtn2ActionPerformed

    private void viewMedicalRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMedicalRecordsActionPerformed
        showForm(new MedicalRecord(this.shelterManager));
        System.out.println("Pass: MEDICAL RECORD - View Medical Records");
    }//GEN-LAST:event_viewMedicalRecordsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       showForm(new AddMedicalRecord(this.shelterManager));
        System.out.println("Pass: MEDICAL RECORD - Add Medical Record");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShelterManager manager = new ShelterManager();
                new MedicalRecordFrame(manager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adoptionProcessingBtn2;
    private javax.swing.JPanel adoptionProcessingPanel2;
    private javax.swing.JButton animalManagementBtn2;
    private javax.swing.JLabel bantayLbl2;
    private javax.swing.JPanel jBody;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logoutBtn2;
    private javax.swing.JButton medicalRecordsBtn2;
    private javax.swing.JButton reportsBtn2;
    private javax.swing.JPanel sidePanel2;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton viewMedicalRecords;
    // End of variables declaration//GEN-END:variables
}
